### ISSUE TITLE
Does this repo accept Pull request ?

### ISSUE THREAD

**Issue by mirtlecn** [jgpaiva/GridMove#23]
GridMove is still a great tool after so many year.

I recently reviewed the code and created a fork version [here](https://github.com/mirtlecn/GridMove), with a lots of bug fixes and some additional functions.

I am glad to contribute to this repo if this repo is still maintained.

**Comment by atlasflux** [comment]
@mirtlecn It seems GridMove has not been maintained for years and I've equally considered it a great tool although have had to fix a bug or two.  Given your enthusiasm for this software, I'm curious if you ended up finding another similar solution that is currently being maintained.  I see you've deprecated your fork so I'm curious what you're using.

**Comment by cutecycle** [comment]
These days personally, I'm using the window snapper in Microsoft/powertoys

**Comment by atlasflux** [comment]
> These days personally, I'm using the window snapper in Microsoft/powertoys

I assume you mean the FancyZones utility?  I've played with that a bit and it's close to what I'd like.  I've just gotten really used to middle clicking anywhere on the window and moving it into a snap region (as GridMove can be configured to do).  It may sound silly but I think it saves me a lot of time to not have to move my mouse cursor up to the window title bar to click to move.  Nevertheless, maybe I'll take a peek at FancyZones again.

**Comment by mirtlecn** [comment]
@atlasflux

Thanks for your reply.

I am still using my forked version Gridmove, and it works perfectly for me.
