### ISSUE TITLE
Command Hotkey does not work with numpad

### ISSUE THREAD

**Issue by JMTyler** [jgpaiva/GridMove#6]
By "Command Hotkey" I mean the shortcut that defaults to #g.

If I change that hotkey to a number, such as #0, I can activate GridMove by pressing Win+0 via the main row of number-keys, but I cannot activate it by pressing Win+0 via the numpad.

**Comment by jgpaiva** [comment]
The problem is that the number-keys are actually different keys. In order to use the numpad zero as a hotkey, you should set the hotkey to `#Numpad0`. See more details [here](http://ahkscript.org/docs/KeyList.htm).
