### ISSUE TITLE
window always on top

### ISSUE THREAD

**Issue by ghost** [jgpaiva/GridMove#7]
I'm trying out version 1.19.62 on win7 64-bit. Overall it works great! (thank you). However, I noticed that once I make a window "On Top" such as with template EdgeGrid, I can't make that window not be on top. Is there a way to cancel that mode?

**Comment by jgpaiva** [comment]
That grid element should be a toggle, dragging the window again to the same grid element should disable "On Top". Isn't that working?

**Comment by ghost** [comment]
Wow! thank you for a super fast response.

I'm currently only using your tool via the keyboard shortcuts. So it never occurred to me to try dragging it to the grid element a second time. That worked fine. Thanks for the tip.

**Comment by jgpaiva** [comment]
Actually, I was convinced that running the same keyboard shortcut again would also toggle the "on top" property :)

**Comment by ghost** [comment]
you're right. That seems to work too. I just didn't notice that.
